import { RouteInfo } from "./sidebar.metadata";


export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Personal",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Dashboard",
    icon: "icon-Car-Wheel",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "/dashboard/dashboard1",
        title: "Dashboard",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      // {
      //     path: '/dashboard/dashboard2',
      //     title: 'Dashboard 2',
      //     icon: '',
      //     class: '',
      //     extralink: false,
      //     submenu: []
      // },
      // {
      //     path: '/dashboard/dashboard3',
      //     title: 'Dashboard 3',
      //     icon: '',
      //     class: '',
      //     extralink: false,
      //     submenu: []
      // }
    ],
  },
  {
    path: "",
    title: "Profile",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },

  {
    path: "",
    title: "Registration",
    icon: "icon-User",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "institute/institutedetails",
        title: "Institute Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "student/addstudent",
        title: "Add Students",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "student/studentdetails",
        title: "Student List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "staff/addstaff",
        title: "Add Staff",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "staff/stafflist",
        title: "Staff List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Class",
    icon: "sl-icon-people",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "class/classlist",
        title: "Class List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Attendence Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Leave",
    icon: " fas fa-user-times",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "leave/leaveapplication",
        title: "Leave Application",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "leave/leavereport",
        title: "Leave Report",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Account Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },

  {
    path: "",
    title: "Fee",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "fee/addfee",
        title: "Add Fee Types",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "fee/viewfeetype",
        title: "View Fee Types",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      // {
      //   path: "fee/studentfeeinfo",
      //   title: "Student Fee Info",
      //   icon: "",
      //   class: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "fee/viewbill",
      //   title: "view Bill",
      //   icon: "",
      //   class: "",
      //   extralink: false,
      //   submenu: [],
      // },
    ],
  },
  {
    path: "",
    title: "Fee Report",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "feereport/paidstudent",
        title: "Fee Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Expense",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "expense/addexpense",
        title: "Add Expense",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "expense/viewexpense",
        title: "View Expense",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Salary",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "salary/addsalary",
        title: "Add Salary Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "salary/salarydetails",
        title: "Salary List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Penalty",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "penalty/addpenalty",
        title: "Add Penalty",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "penalty/penaltylist",
        title: "Penalty List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Income",
    icon: "icon-Money",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "income/incomedetails",
        title: "Income Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "income/addfund",
        title: "Add Funds",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "income/funddetails",
        title: "Fund List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Event Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },

  {
    path: "",
    title: "Calender",
    icon: "icon-User",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "calender/schoolcalender",
        title: "School Calender",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Student Activities",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Homework",
    icon: "icon-Books",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "homework/addhomework",
        title: "Add Homework",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "homework/homeworklist",
        title: "Homework List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },


  {
    path: "",
    title: "Exam",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Exam",
    icon: "icon-Books",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "exam/addexam",
        title: "Add exam",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "exam/listexam",
        title: "list Exam",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "exam/addmark",
        title: "add marksheet",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "exam/showmarksheet",
        title: "show marks",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
     
    ],
  },
  // {
  //   path: "",
  //   title: "Classwork",
  //   icon: "icon-Books",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "homework/addclasswork",
  //       title: "Add Classwork",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "homework/classworklist",
  //       title: "Classwork List",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: "",
    title: "Time Table Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Time Table",
    icon: "icon-Split-FourSquareWindow",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "timetable/addtimetable",
        title: "Create Time Table",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "timetable/listtimetable",
        title: "Time Table List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      // {
      //   path: "timetable/availableteacher",
      //   title: "Available Teachers",
      //   icon: "",
      //   class: "",
      //   extralink: false,
      //   submenu: [],
      // },
    ],
  },
  {
    path: "",
    title: "Vehicle Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Manage Vehicle",
    icon: "icon-Bus",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "vehicle/vehiclelist",
        title: "Registration Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Manage Route",
    icon: "icon-Bus",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "root/rootlist",
        title: "Route Details",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Track Vehicle",
    icon: "icon-Bus",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "transportmap/Tranportmap",
        title: "View Map",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Student Report",
    icon: "icon-Bus",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "transreport/studreport",
        title: "Student Report",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      // {
      //   path: "transreport/staffreport",
      //   title: "Staff Report",
      //   icon: "",
      //   class: "",
      //   extralink: false,
      //   submenu: [],
      // },
    ],
  },

  {
    path: "",
    title: "Library Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Books",
    icon: " sl-icon-book-open",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "book/addbook",
        title: "Register Books",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "book/booklist",
        title: "List of Books",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      }
     
    ],
  },
  {
    path: "",
    title: "Pending Books",
    icon: " sl-icon-book-open",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "book/pendingbook",
        title: "Pending Books List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Issue Books",
    icon: " sl-icon-book-open",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "issued/issuedreg",
        title: "Issue Book",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "issued/issuedlist",
        title: "Book Issue List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Recieved Books",
    icon: " sl-icon-book-open",
    class: "has-arrow",
    extralink: false,
    submenu: [
      // {
      //   path: "recieved/addrecieve",
      //   title: "Register Recieved Books",
      //   icon: "",
      //   class: "",
      //   extralink: false,
      //   submenu: [],
      // },
      {
        path: "recieved/recievedlist",
        title: " Recieved Books List",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },



  {
    path: "",
    title: "Notification Management",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Notifications",
    icon: " sl-icon-book-open",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "notification/sendnoty",
        title: "Send Notification",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "notification/listnoty",
        title: "Notice Board",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Competetion",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: "Quiz",
    icon: "icon-Split-FourSquareWindow",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
        path: "quiz/intro",
        title: "Take a Quiz",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "quiz/addquestion",
        title: "Add Quiz",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },

      {
        path: "quiz/listquestion",
        title: "List Question",
        icon: "",
        class: "",
        extralink: false,
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Forum",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "",
    title: " Group Chat",
    icon: "icon-Books",
    class: "has-arrow",
    extralink: false,
    submenu: [
      {
          path: "group-chat/chatbox",
          title: 'Send Message',
          icon: '',
          class: '',
          extralink: false,
          submenu: []
      }
      // {
      //     path: 'leave/leavereport',
      //     title: 'Leave Report',
      //     icon: '',
      //     class: '',
      //     extralink: false,
      //     submenu: []
      // },
    ],
  },

  // {
  //   path: "",
  //   title: "UI",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "UI Elements",
  //   icon: "icon-Paint-Brush",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/component/accordion",
  //       title: "Accordion",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/alert",
  //       title: "Alert",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/carousel",
  //       title: "Carousel",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/dropdown",
  //       title: "Dropdown",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/modal",
  //       title: "Modal",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/pagination",
  //       title: "Pagination",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/poptool",
  //       title: "Popover & Tooltip",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/progressbar",
  //       title: "Progressbar",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/rating",
  //       title: "Ratings",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/tabs",
  //       title: "Tabs",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/timepicker",
  //       title: "Timepicker",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/buttons",
  //       title: "Button",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/notifier",
  //       title: "Notifier",
  //       icon: "mdi mdi-bandcamp",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Cards",
  //   icon: "icon-Folder-Add",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/cards/basiccards",
  //       title: "Basic Cards",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/cards/customcards",
  //       title: "Custom Cards",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/cards/weathercards",
  //       title: "Weather Cards",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Extra Components",
  //   icon: "icon-Idea-5",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/extra-component/toastr",
  //       title: "Toastr",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/extra-component/editor",
  //       title: "Editor",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/extra-component/dragndrop",
  //       title: "Drag n Drop",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Widgets",
  //   icon: "icon-Wrench",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/widgets/apps",
  //       title: "Widget Apps",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/widgets/data",
  //       title: "Widget Data",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Forms",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Form Elements",
  //   icon: "icon-Receipt-4",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/forms/forminputs",
  //       title: "Form Inputs",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/inputgroups",
  //       title: "Input Groups",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/inputgrid",
  //       title: "Input Grid",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/checkboxandradio",
  //       title: "Checkbox & Radio",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/multiselect",
  //       title: "Multiselect",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Form Layouts",
  //   icon: "icon-Receipt-2",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/forms/formbasic",
  //       title: "Basic Forms",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/formhorizontal",
  //       title: "Horizontal Forms",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/formactions",
  //       title: "Form Actions",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/formrowseparator",
  //       title: "Row Separator",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/formstripedrows",
  //       title: "Striped Rows",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/formdetail",
  //       title: "Detail Forms",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Form Addons",
  //   icon: "icon-Add",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/forms/formvalidation",
  //       title: "Form Validation",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/typehead",
  //       title: "Form Typehead",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/datepicker",
  //       title: "Datepicker",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/component/language-datepicker",
  //       title: "Language Datepicker",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/forms/ngx",
  //       title: "Form Wizard / Steps",
  //       icon: "mdi mdi-attachment",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Tables",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Bootstrap Tables",
  //   icon: "mdi mdi-border-none",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/tables/basictables",
  //       title: "Basic Tables",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/tables/darktables",
  //       title: "Dark Basic Tables",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/tables/colortables",
  //       title: "Colored Tables",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/tables/tablesizing",
  //       title: "Table Sizing",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "/tables/datatable",
  //   title: "Data Tables",
  //   icon: "mdi mdi-border-vertical",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Charts",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Charts",
  //   icon: "icon-Pie-Chart",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/charts/chartjs",
  //       title: "Chart Js",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/charts/chartistjs",
  //       title: "Chartist Js",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/charts/ngxchart",
  //       title: "Ngx Charts",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Maps",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "/maps/google",
  //   title: "Google Maps",
  //   icon: "icon-Location-2",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Pages",
  //   icon: "mdi mdi-dots-horizontal",
  //   class: "nav-small-cap",
  //   extralink: true,
  //   submenu: [],
  // },
  // {
  //   path: "",
  //   title: "Ecommerce Pages",
  //   icon: "icon-Shopping-Bag",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/ecom/products",
  //       title: "Products",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/ecom/cart",
  //       title: "Cart",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/ecom/edit",
  //       title: "Edit Products",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/ecom/details",
  //       title: "Product Details",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/ecom/orders",
  //       title: "Orders",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/ecom/checkout",
  //       title: "Checkout",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Authentication",
  //   icon: "icon-Administrator",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/authentication/login",
  //       title: "Login",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/login2",
  //       title: "Login 2",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/signup",
  //       title: "Register",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/signup2",
  //       title: "Register 2",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/404",
  //       title: "404",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/authentication/lock",
  //       title: "Lockscreen",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Sample Pages",
  //   icon: "icon-Files",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/sample-pages/profile",
  //       title: "Profile",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/sample-pages/pricing",
  //       title: "Pricing",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/sample-pages/invoice",
  //       title: "Invoice",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/sample-pages/helperclasses",
  //       title: "Helper Classes",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/starter",
  //       title: "Starter Page",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Timeline",
  //   icon: "mdi mdi-apple-safari",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/timeline/left",
  //       title: "Left Timeline",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/timeline/right",
  //       title: "Right Timeline",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/timeline/center",
  //       title: "Center Timeline",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Icons",
  //   icon: "icon-Eyeglasses-Smiley",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "/icons/fontawesome",
  //       title: "Fontawesome",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/icons/simpleline",
  //       title: "Simple Line Icons",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/icons/material",
  //       title: "Material Icons",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //     {
  //       path: "/icons/iconmind",
  //       title: "Iconmind Icons",
  //       icon: "",
  //       class: "",
  //       extralink: false,
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Menu Levels",
  //   icon: "mdi mdi-notification-clear-all",
  //   class: "has-arrow",
  //   extralink: false,
  //   submenu: [
  //     {
  //       path: "",
  //       title: "Second Level",
  //       icon: "",
  //       class: "",
  //       extralink: true,
  //       submenu: [],
  //     },
  //     {
  //       path: "",
  //       title: "Second Child",
  //       icon: "",
  //       class: "has-arrow",
  //       extralink: false,
  //       submenu: [
  //         {
  //           path: "",
  //           title: "Third 1.1",
  //           icon: "",
  //           class: "",
  //           extralink: false,
  //           submenu: [],
  //         },
  //         {
  //           path: "",
  //           title: "Third 1.2",
  //           icon: "",
  //           class: "",
  //           extralink: false,
  //           submenu: [],
  //         },
  //       ],
  //     },
  //   ],
  // },
];
